import {Ride,STEP} from './physics.js';
import {Gestures} from './input.js';
import {RIDERS,BOARDS,CUL_START,LENGTH,roadPoints,route,throatPolygon,bulb,pixel,ROAD_HALF,SCALE,clamp} from './world.js';
const $=id=>document.getElementById(id),root=$('game');
let view,sim,active=false,paused=false,last=0,accumulator=0,selection={rider:'DOG',board:'LONGBOARD',rope:.45,seed:8},hintUntil=0,lastLap=0,finishedShown=false;
const dev=new URLSearchParams(location.search).has('debug');$('debug').hidden=!dev;
function fail(e){$('errorText').textContent='The game couldn’t load. Please reload or open it in Chrome or Safari.';$('error').hidden=false;console.error(e);}
window.addEventListener('error',e=>fail(e.error));window.addEventListener('unhandledrejection',e=>fail(e.reason));
try{const saved=JSON.parse(localStorage.getItem('track-03-selection')||'null');if(saved&&RIDERS[saved.rider]&&BOARDS[saved.board])selection={...selection,...saved,rope:clamp(Number(saved.rope)||0,0,1)};}catch{}
class Sound {
 constructor(){this.enabled=true;this.ctx=null;}
 async start(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();const a=this.ctx;this.master=a.createGain();this.master.gain.value=.12;this.master.connect(a.destination);this.engine=a.createOscillator();this.engine.type='triangle';this.eg=a.createGain();this.eg.gain.value=.17;this.engine.connect(this.eg).connect(this.master);this.engine.start();const data=a.createBuffer(1,a.sampleRate*2,a.sampleRate),arr=data.getChannelData(0);for(let i=0;i<arr.length;i++)arr[i]=Math.random()*2-1;this.noise=a.createBufferSource();this.noise.buffer=data;this.noise.loop=true;this.filter=a.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=300;this.ng=a.createGain();this.ng.gain.value=0;this.noise.connect(this.filter).connect(this.ng).connect(this.master);this.noise.start();}await this.ctx.resume();}catch{this.enabled=false;$('sound').textContent='Sound off';}}
 update(){if(!this.ctx)return;const t=this.ctx.currentTime,sp=Math.hypot(sim.rider.vx,sim.rider.vz);this.master.gain.setTargetAtTime(active&&!paused&&this.enabled?.12:0,t,.2);this.engine.frequency.setTargetAtTime(43+sim.car.speed*5,t,.2);this.ng.gain.setTargetAtTime(sim.phase==='crashed'?.3:Math.min(.38,sp*.035),t,.15);this.filter.frequency.setTargetAtTime(350+sp*85,t,.1);}
}
const sound=new Sound();
function hint(text,seconds=5){$('hint').textContent=text;hintUntil=performance.now()+seconds*1000;}
const gesture=new Gestures({release:()=>{if(active&&!paused&&sim.release())hint('Easy. Coast it out. The crew’s stopping.',5);},ollie:()=>{if(active&&!paused)sim.ollie();}});
function updateSelection(){const o=selection;$('riderName').textContent=o.rider;$('driverName').textContent=(o.rider==='DOG'?'SALLY':'DOG')+'’S DRIVING';$('boardName').textContent=BOARDS[o.board].label;$('rope').value=o.rope*100;
 const cv=$('boardPreview'),c=cv.getContext('2d');c.clearRect(0,0,220,44);const b=BOARDS[o.board],w=b.length*155;c.fillStyle=o.board==='CRUISER'?'#b77158':o.board==='STREET'?'#8d9da0':'#bcab7e';c.beginPath();c.roundRect((220-w)/2,13,w,17,[9]);c.fill();c.strokeStyle='#32424c';c.lineWidth=3;c.beginPath();c.moveTo((220-w)/2+19,8);c.lineTo((220-w)/2+19,35);c.moveTo((220+w)/2-19,8);c.lineTo((220+w)/2-19,35);c.stroke();
 if(view){sim=new Ride(selection);view.setSelection(selection);view.camPos=null;}try{localStorage.setItem('track-03-selection',JSON.stringify(selection));}catch{}
}
function cycle(type,dir){if(active)return;const keys=Object.keys(type==='rider'?RIDERS:BOARDS);selection[type]=keys[(keys.indexOf(selection[type])+dir+keys.length)%keys.length];updateSelection();}
$('riderPrev').onclick=()=>cycle('rider',-1);$('riderNext').onclick=()=>cycle('rider',1);$('boardPrev').onclick=()=>cycle('board',-1);$('boardNext').onclick=$('boardForward').onclick=()=>cycle('board',1);$('rope').oninput=e=>{selection.rope=Number(e.target.value)/100;updateSelection();};
function start(options={}){if(!view)return;selection.seed++;sim=new Ride({...selection,...options});view.setSelection(selection);view.camPos=null;active=true;paused=false;finishedShown=false;accumulator=0;lastLap=0;gesture.reset();root.classList.add('playing');$('toolbar').hidden=false;$('panel').hidden=true;$('instructions').hidden=true;$('lapMessage').textContent='';$('scene').focus();sound.start();hint('Drag to carve · Hold to crouch · Flick up to let go',9);}
$('start').onclick=()=>start();
function showPanel(kind){$('panel').hidden=false;const cfg=kind==='pause'?['TAKE A BREATH','Still here.','The evening can wait.','Keep riding']:kind==='regroup'?['EVERYBODY GOOD?','Grab the rope.','The car’s stopped. Take a moment, then tow from here.','Another tow']:['THE CREW’S STOPPING','You good?','Give it a second. The next run starts back at the line.','One more run'];$('panelKicker').textContent=cfg[0];$('panelTitle').textContent=cfg[1];$('panelBody').textContent=cfg[2];$('resume').textContent=cfg[3];$('hint').textContent='';}
function togglePause(){if(!active||['ended','regroup'].includes(sim.phase))return;paused=!paused;gesture.reset();keys.clear();accumulator=0;sound.update();if(paused)showPanel('pause');else{$('panel').hidden=true;$('scene').focus();sound.start();}}
$('pause').onclick=togglePause;
$('resume').onclick=()=>{if(sim.phase==='ended')start();else if(sim.phase==='regroup'){const s=sim.car.s,time=sim.time;start({start:s});sim.time=time;lastLap=sim.laps=Math.floor(s/LENGTH);hint('All right. Nice and easy.',4);}else if(paused)togglePause();};
$('restart').onclick=()=>{active=false;paused=false;gesture.reset();root.classList.remove('playing');$('panel').hidden=true;$('toolbar').hidden=true;$('hint').textContent='';updateSelection();};
$('how').onclick=()=>{$('instructions').hidden=false;};$('closeHow').onclick=()=>{$('instructions').hidden=true;};
$('sound').onclick=()=>{sound.enabled=!sound.enabled;$('sound').textContent=sound.enabled?'Sound on':'Sound off';$('sound').setAttribute('aria-label',sound.enabled?'Turn sound off':'Turn sound on');if(sound.enabled)sound.start();};
const canvas=$('scene');canvas.addEventListener('pointerdown',e=>{if(!active||paused||e.button>0)return;canvas.setPointerCapture(e.pointerId);gesture.down(e.pointerId,e.clientX,e.clientY,performance.now());});canvas.addEventListener('pointermove',e=>{if(active&&!paused)gesture.move(e.pointerId,e.clientX,e.clientY,performance.now());});canvas.addEventListener('pointerup',e=>gesture.up(e.pointerId,performance.now()));canvas.addEventListener('pointercancel',e=>gesture.cancel(e.pointerId));canvas.addEventListener('lostpointercapture',e=>gesture.cancel(e.pointerId));canvas.addEventListener('contextmenu',e=>e.preventDefault());
const keys=new Set();window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['ArrowLeft','ArrowRight','ArrowUp',' ','Escape'].includes(e.key)){e.preventDefault();if(e.key==='Escape'&&!e.repeat)togglePause();if(!active||paused)return;keys.add(e.key);if(e.key==='ArrowUp'&&!e.repeat)gesture.actions.release();}});window.addEventListener('keyup',e=>{if(e.key===' '&&keys.has(' ')&&active&&!paused)sim.ollie();keys.delete(e.key);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused)togglePause();last=0;keys.clear();gesture.reset();});window.addEventListener('blur',()=>{keys.clear();gesture.reset();});window.addEventListener('resize',()=>view?.resize());
$('lab').onclick=()=>start({start:CUL_START-45});$('stress').onclick=()=>start({start:CUL_START-60,speedFactor:1.7});
function debug(){if(!dev)return;const ctx=$('map').getContext('2d'),sx=p=>(p.x/SCALE+693-520)*1.13,sz=p=>(p.z/SCALE+339-275)*1.13;ctx.fillStyle='#152332';ctx.fillRect(0,0,340,390);const trace=(ps,close)=>{ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(sx(p),sz(p)):ctx.moveTo(sx(p),sz(p)));if(close)ctx.closePath();};ctx.lineWidth=ROAD_HALF*2/SCALE*1.13;ctx.strokeStyle='#818c90';trace(roadPoints,true);ctx.stroke();ctx.fillStyle='#818c90';trace(throatPolygon,true);ctx.fill();ctx.beginPath();ctx.arc(sx(bulb),sz(bulb),bulb.r/SCALE*1.13,0,7);ctx.fill();ctx.strokeStyle='#cdb279';ctx.lineWidth=1;trace(route,true);ctx.stroke();for(const [p,color]of [[sim.car,'#fc7954'],[sim.rider,'#faf3d9']]){ctx.fillStyle=color;ctx.beginPath();ctx.arc(sx(p),sz(p),3,0,7);ctx.fill();}$('telemetry').textContent=`${sim.phase} · ${sim.driver} driving\nlap ${sim.laps+1} · ${sim.car.speed.toFixed(2)} m/s\nrope ${sim.rope.toFixed(2)} m · pull ${sim.rider.tension.toFixed(2)} m/s²\nwobble ${sim.rider.wobble.toFixed(2)} · ${view.renderer.info.render.calls} draws`;}
function frame(t){try{const dt=last?Math.min((t-last)/1000,.1):1/60;last=t;gesture.tick(t);const input={...gesture.state};if(keys.has('ArrowLeft'))input.steer=-.7;if(keys.has('ArrowRight'))input.steer=.7;if(keys.has(' '))input.crouch=true;
 if(active&&!paused){accumulator+=dt;while(accumulator>=STEP){sim.step(input);accumulator-=STEP;}if(sim.laps>lastLap){lastLap=sim.laps;$('lapMessage').textContent='AROUND AGAIN';setTimeout(()=>{$('lapMessage').textContent='';},3500);}if(['ended','regroup'].includes(sim.phase)&&!finishedShown){finishedShown=true;showPanel(sim.phase);}}
 if(t>hintUntil)$('hint').textContent='';view.draw(sim,dt,input,!active);sound.update();if(dev)debug();requestAnimationFrame(frame);}catch(e){fail(e);}}
try{const {View}=await import('./render.js');view=new View(canvas);updateSelection();$('load').hidden=true;$('start').disabled=false;requestAnimationFrame(frame);}catch(e){fail(e);}
if('serviceWorker'in navigator&&!dev)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
// Feature-detected read-only integration uses the live state, not a second model.
try{document.modelContext?.registerTool({name:'read_ride_state',description:'Read the current Track ride, selections, driver, lap, pause and offline readiness.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('No arguments expected');return{selection,active,paused,phase:sim.phase,driver:sim.driver,lap:sim.laps+1,offlineReady:!!navigator.serviceWorker?.controller};}});}catch{}
if(dev)window.trackDebug={snapshot:()=>sim.snapshot(),start,release:()=>sim.release(),step:(n,input={})=>{for(let i=0;i<n;i++)sim.step(input);return sim.snapshot();},pause:()=>{paused=true;},get view(){return view;}};

