import * as T from './vendor/three.module.js';
import {entrancePoints,entranceJunction,ENTRANCE_HOUSES,roadPoints,throatPolygon,bulb,ROAD_HALF,roadDistance,FOOTPATH,height,sample,heading,curvature,point,aerialPoint,clamp,mix,angle,RIDERS,BOARDS} from './world.js';
const UP=new T.Vector3(0,1,0);
export class View {
 constructor(canvas){this.canvas=canvas;this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power',alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.scene=new T.Scene();this.scene.fog=new T.FogExp2(0x596773,.0045);this.camera=new T.PerspectiveCamera(58,1,.12,620);this.hemi=new T.HemisphereLight(0xa6c5d8,0x504232,2.1);this.scene.add(this.hemi);this.sunlight=new T.DirectionalLight(0xffd0a0,1.7);this.sunlight.position.set(-80,55,-90);this.scene.add(this.sunlight);this.materials={};this.tails=[];this.lamps=[];this.randomSeed=1208;this.camHeading=heading(0);this.camPos=null;this.buildWorld();this.car=this.makeCar();this.scene.add(this.car);this.rider=this.makeRider();this.scene.add(this.rider);this.ropePositions=new Float32Array(33*3);const rg=new T.BufferGeometry();rg.setAttribute('position',new T.BufferAttribute(this.ropePositions,3));this.rope=new T.Line(rg,new T.LineBasicMaterial({color:0xd9cda8,transparent:true,opacity:.95}));this.rope.frustumCulled=false;this.scene.add(this.rope);this.handle=this.box(.42,.035,.035,0xddd0a7);this.scene.add(this.handle);this.board=this.makeBoard();this.scene.add(this.board);this.resize();}
 rand(){let t=this.randomSeed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}
 mat(color){return this.materials[color]??=new T.MeshStandardMaterial({color,roughness:1,flatShading:true});}
 box(x,y,z,color){return new T.Mesh(new T.BoxGeometry(x,y,z),this.mat(color));}
 addBox(group,w,h,d,color,x,y,z){const m=this.box(w,h,d,color);m.position.set(x,y,z);group.add(m);return m;}
 cylinder(r1,r2,h,color,n=7){return new T.Mesh(new T.CylinderGeometry(r1,r2,h,n),this.mat(color));}
 buildWorld(){
  const skyGeo=new T.SphereGeometry(580,24,12);const skyMat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color('#526e87')},bottom:{value:new T.Color('#d8b08a')}},vertexShader:'varying vec3 vWorld; void main(){vec4 p=modelMatrix*vec4(position,1.);vWorld=position;gl_Position=projectionMatrix*viewMatrix*p;}',fragmentShader:'uniform vec3 top;uniform vec3 bottom;varying vec3 vWorld;void main(){float h=clamp(normalize(vWorld).y*1.7,0.,1.);gl_FragColor=vec4(mix(bottom,top,pow(h,.55)),1.);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'});this.sky=new T.Mesh(skyGeo,skyMat);this.scene.add(this.sky);
  const terrain=new T.PlaneGeometry(1050,1050,85,85);terrain.rotateX(-Math.PI/2);const pa=terrain.attributes.position;const colors=[];for(let i=0;i<pa.count;i++){const x=pa.getX(i),z=pa.getZ(i);pa.setY(i,height(x,z)-.035);const c=new T.Color().setHSL(.072+this.rand()*.022,.19+this.rand()*.08,.067+this.rand()*.018);colors.push(c.r,c.g,c.b);}terrain.setAttribute('color',new T.Float32BufferAttribute(colors,3));terrain.computeVertexNormals();const land=new T.Mesh(terrain,new T.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:true}));this.scene.add(land);
  this.asphalt=new T.MeshStandardMaterial({color:0x343e46,roughness:1});this.asphalt.polygonOffset=true;this.asphalt.polygonOffsetFactor=-1;this.asphalt.polygonOffsetUnits=-1;
  this.ribbon(roadPoints,ROAD_HALF,this.asphalt,true);this.ribbon(entrancePoints,ROAD_HALF,this.asphalt,false);this.flatPoly(entranceJunction,this.asphalt,.025);this.flatPoly(throatPolygon,this.asphalt,.025);
  const disk=[];for(let i=0;i<96;i++){const a=i/96*Math.PI*2;disk.push({x:bulb.x+Math.cos(a)*bulb.r,z:bulb.z+Math.sin(a)*bulb.r});}this.flatPoly(disk,this.asphalt,.026);
  // Curbs are clipped against the union, so the bulb has no invisible inner ring.
  const curbSegments=[];const edges=[];for(const side of [-1,1]){const e=roadPoints.map((p,i)=>{const a=roadPoints[(i-1+roadPoints.length)%roadPoints.length],b=roadPoints[(i+1)%roadPoints.length],h=Math.atan2(b.z-a.z,b.x-a.x);return{x:p.x-Math.sin(h)*ROAD_HALF*side,z:p.z+Math.cos(h)*ROAD_HALF*side};});edges.push(e);}edges.push(disk,throatPolygon,entranceJunction);
  const entrySides=[-1,1].map(side=>entrancePoints.map((p,i)=>{const a=entrancePoints[Math.max(0,i-1)],b=entrancePoints[Math.min(entrancePoints.length-1,i+1)],h=Math.atan2(b.z-a.z,b.x-a.x);return{x:p.x-Math.sin(h)*ROAD_HALF*side,z:p.z+Math.cos(h)*ROAD_HALF*side};}));edges.push([...entrySides[0],...entrySides[1].reverse()]);
  for(const edge of edges)for(let i=0;i<edge.length;i++){const a=edge[i],b=edge[(i+1)%edge.length],n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/.6));for(let j=0;j<n;j++){const p={x:mix(a.x,b.x,j/n),z:mix(a.z,b.z,j/n)},q={x:mix(a.x,b.x,(j+1)/n),z:mix(a.z,b.z,(j+1)/n)};if(roadDistance((p.x+q.x)/2,(p.z+q.z)/2)>-.08)curbSegments.push([p,q]);}}
  const positions=[];for(const [p,q]of curbSegments){const dx=q.x-p.x,dz=q.z-p.z,l=Math.hypot(dx,dz),nx=-dz/l*.18,nz=dx/l*.18;const a=[p.x+nx,height(p.x,p.z)+.13,p.z+nz],b=[p.x-nx,height(p.x,p.z)+.13,p.z-nz],c=[q.x+nx,height(q.x,q.z)+.13,q.z+nz],d=[q.x-nx,height(q.x,q.z)+.13,q.z-nz];positions.push(...a,...b,...c,...b,...d,...c);}const cg=new T.BufferGeometry();cg.setAttribute('position',new T.Float32BufferAttribute(positions,3));cg.computeVertexNormals();this.scene.add(new T.Mesh(cg,new T.MeshStandardMaterial({color:0xbbb8a5,roughness:1,side:T.DoubleSide})));
  this.ribbon(FOOTPATH,.73,this.mat(0x949282),false,.015);
  // Instanced woodland keeps the phone scene inexpensive.
  const treeGeo=new T.IcosahedronGeometry(1,0),treeMat=new T.MeshStandardMaterial({color:0xffffff,roughness:1,flatShading:true});const crowns=new T.InstancedMesh(treeGeo,treeMat,750);const trunks=new T.InstancedMesh(new T.CylinderGeometry(.17,.26,1,5),this.mat(0x3c3934),750);const ob=new T.Object3D();let count=0;
  for(let i=0;i<3500&&count<750;i++){const x=-280+this.rand()*520,z=-180+this.rand()*650,p=point(693+x/.91,339+z/.91);const interior=x>-102&&x<70&&z>5&&z<222;const clearance=roadDistance(x,z);if(clearance<20||interior||ENTRANCE_HOUSES.some(h=>Math.hypot(x-h.x,z-h.z)<22))continue;const h=5+this.rand()*9,y=height(x,z),r=3+this.rand()*3;ob.position.set(x,y+h*.68,z);ob.rotation.set(this.rand(),this.rand()*6,this.rand());ob.scale.set(r,h*.48,r);ob.updateMatrix();crowns.setMatrixAt(count,ob.matrix);crowns.setColorAt(count,new T.Color().setHSL(.27+this.rand()*.06,.12+this.rand()*.12,.025+this.rand()*.025));ob.position.set(x,y+h*.27,z);ob.rotation.set(0,0,0);ob.scale.set(1,h*.54,1);ob.updateMatrix();trunks.setMatrixAt(count,ob.matrix);count++;}crowns.count=count;trunks.count=count;this.scene.add(crowns,trunks);
  // Weeds and unfinished utilities. No sidewalks, mailboxes or centre lines.
  const weeds=new T.InstancedMesh(new T.ConeGeometry(.3,.8,3),this.mat(0x686a4a),480);let wi=0;for(let i=0;i<1600&&wi<480;i++){const x=-175+this.rand()*295,z=-30+this.rand()*285;if(roadDistance(x,z)<1.5)continue;ob.position.set(x,height(x,z)+.25,z);ob.rotation.set(0,this.rand()*6,0);ob.scale.set(1,.4+this.rand(),1);ob.updateMatrix();weeds.setMatrixAt(wi++,ob.matrix);}weeds.count=wi;this.scene.add(weeds);
  for(let i=0;i<14;i++){const s=28+i*55,p=sample(s),h=heading(s),side=i%2?1:-1;this.lamp(p.x-Math.sin(h)*(ROAD_HALF+1.1)*side,p.z+Math.cos(h)*(ROAD_HALF+1.1)*side,h,side);}
  for(const s of [115,405,550,665]){const p=sample(s);const m=new T.Mesh(new T.CylinderGeometry(.36,.36,.015,20),this.mat(0x55595a));m.position.set(p.x,height(p.x,p.z)+.035,p.z);this.scene.add(m);}
  for(let i=0;i<9;i++){const a=this.rand()*6.28,r=this.rand()*2.8;const m=this.box(.15+this.rand()*.3,.12,.25,0x898375);m.position.set(bulb.x+Math.cos(a)*r,.075,bulb.z+Math.sin(a)*r);m.rotation.y=a;this.scene.add(m);}
  this.gateAndHouses();
 }
 flatPoly(points,mat,lift=0){const shape=new T.Shape(points.map(p=>new T.Vector2(p.x,-p.z))),g=new T.ShapeGeometry(shape);g.rotateX(-Math.PI/2);const p=g.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,height(p.getX(i),p.getZ(i))+lift);g.computeVertexNormals();this.scene.add(new T.Mesh(g,mat));}
 ribbon(points,width,mat,closed=false,lift=.022){const pos=[];for(let i=0;i<(closed?points.length:points.length-1);i++){const a=points[i],b=points[(i+1)%points.length],p0=points[(i-1+points.length)%points.length],p2=points[(i+2)%points.length];const ha=!closed&&i===0?Math.atan2(b.z-a.z,b.x-a.x):Math.atan2(b.z-p0.z,b.x-p0.x),hb=!closed&&i===points.length-2?ha:Math.atan2(p2.z-a.z,p2.x-a.x);const v=(p,h,s)=>{const x=p.x-Math.sin(h)*width*s,z=p.z+Math.cos(h)*width*s;return[x,height(x,z)+lift,z];};const al=v(a,ha,-1),ar=v(a,ha,1),bl=v(b,hb,-1),br=v(b,hb,1);pos.push(...al,...bl,...ar,...ar,...bl,...br);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.computeVertexNormals();const mesh=new T.Mesh(g,mat);mesh.material.side=T.DoubleSide;this.scene.add(mesh);}
 lamp(x,z,h,side){const g=new T.Group(),y=height(x,z);g.position.set(x,y,z);const pole=this.cylinder(.055,.085,5.5,0x414344);pole.position.y=2.75;g.add(pole);const head=this.box(.55,.15,.28,0x444647);head.position.set(0,5.5,0);g.add(head);const glow=new T.Mesh(new T.SphereGeometry(.12,8,4),new T.MeshBasicMaterial({color:0xffd286}));glow.position.y=5.4;g.add(glow);this.lamps.push(glow);const pool=new T.Mesh(new T.CircleGeometry(4.2,24),new T.MeshBasicMaterial({color:0xebba6f,transparent:true,opacity:.08,depthWrite:false}));pool.rotation.x=-Math.PI/2;pool.position.set(Math.sin(h)*side*2,.04,-Math.cos(h)*side*2);g.add(pool);this.lamps.push(pool);this.scene.add(g);}
 gateAndHouses(){
  const gate=new T.Group(),p=aerialPoint(852,155);gate.position.set(p.x,height(p.x,p.z),p.z);gate.rotation.y=1.15;
  for(const x of [-5.2,5.2]){this.addBox(gate,.65,2.25,.65,0xe1ddd0,x,1.125,0);this.addBox(gate,.88,.16,.88,0xe9e4d7,x,2.3,0);}
  for(const side of [-1,1]){for(let i=0;i<11;i++)this.addBox(gate,.04,1.6,.04,0x303537,side*(5.5+i*.38),.85,0);this.addBox(gate,4,.06,.06,0x303537,side*7.45,1.5,0);}this.scene.add(gate);
  const hipRoof=(g,w,d,h,y,x,z,color)=>{const r=Math.max(0,(w-d)*.5),v=[[-w/2,0,-d/2],[w/2,0,-d/2],[w/2,0,d/2],[-w/2,0,d/2],[-r,h,0],[r,h,0]],idx=[0,4,5,0,5,1,1,5,2,2,5,4,2,4,3,3,4,0];const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(idx.flatMap(i=>v[i]),3));geo.computeVertexNormals();const mat=this.mat(color);mat.side=T.DoubleSide;const m=new T.Mesh(geo,mat);m.position.set(x,y,z);g.add(m);};
  for(const h of ENTRANCE_HOUSES){const g=new T.Group();g.name=h.name;g.position.set(h.x,height(h.x,h.z),h.z);g.rotation.y=h.rotation;
   this.addBox(g,h.width,5.4,h.depth,h.wall,0,2.7,0);hipRoof(g,h.width+1,h.depth+1,3.3,5.4,0,0,h.roof);
   this.addBox(g,7,3.2,8,h.wall,-h.width*.35,1.6,h.depth*.4);hipRoof(g,8,9,2.4,3.2,-h.width*.35,h.depth*.4,h.roof);
   this.addBox(g,5.6,2.3,.08,0xaaa698,-h.width*.35,1.3,h.depth*.4+4.05);
   for(const x of [-3,2.5,5.5])for(const y of [1.8,4.1]){this.addBox(g,1.35,1.5,.16,0xe3dfd1,x,y,h.depth/2+.08);this.addBox(g,1.1,1.24,.18,0x40535c,x,y,h.depth/2+.15);}
   this.addBox(g,1.1,2.2,.18,0x574739,.2,1.1,h.depth/2+.18);this.addBox(g,2.2,.15,1.5,0xd5ccba,.2,2.4,h.depth/2+.7);
   const front={x:h.x+Math.sin(h.rotation)*(h.depth*.5+1),z:h.z+Math.cos(h.rotation)*(h.depth*.5+1)};this.ribbon([front,h.drive],2.6,this.mat(0xaaa99d),false,.03);this.scene.add(g);
  }
 }
 makeCar(){const g=new T.Group();this.addBox(g,1.77,.65,4.62,0x171e24,0,.72,0);this.addBox(g,1.7,.15,4.6,0x343b3c,0,.44,0);this.addBox(g,1.68,.12,4.35,0x252d31,0,1.08,0);this.addBox(g,1.46,.63,2.1,0x1b242b,0,1.37,-.18);this.addBox(g,1.36,.43,.025,0x49606a,0,1.43,.88);this.addBox(g,1.36,.44,.025,0x4e6875,0,1.43,-1.24);for(const side of [-1,1]){this.addBox(g,.022,.43,1.86,0x425863,side*.743,1.43,-.17);this.addBox(g,.045,.46,.075,0x242b2e,side*.759,1.43,-.12);for(const z of [-1.44,1.42]){const wheel=new T.Mesh(new T.CylinderGeometry(.31,.31,.16,12),this.mat(0x161b1e));wheel.rotation.z=Math.PI/2;wheel.position.set(side*.87,.34,z);g.add(wheel);const hub=new T.Mesh(new T.CylinderGeometry(.18,.18,.17,10),this.mat(0x62696a));hub.rotation.z=Math.PI/2;hub.position.copy(wheel.position);g.add(hub);}}
 this.addBox(g,1.75,.045,.035,0x9b9c92,0,.76,2.325);this.addBox(g,1.63,.045,.03,0x9b9c92,0,.73,-2.325);for(const x of [-.61,.61]){const tail=new T.Mesh(new T.BoxGeometry(.46,.2,.04),new T.MeshBasicMaterial({color:0x9d352a}));tail.position.set(x,.9,2.335);g.add(tail);this.tails.push(tail);this.addBox(g,.14,.055,.045,0xa26e35,x+Math.sign(x)*.12,.95,2.34);}this.addBox(g,.45,.19,.025,0xb3b4a5,0,.62,2.34);const star=new T.Mesh(new T.TorusGeometry(.061,.008,4,16),this.mat(0xbbbbb2));star.position.set(0,1.01,2.342);g.add(star);for(let i=0;i<3;i++){const ray=this.box(.009,.06,.009,0xbbbbb2);ray.position.set(Math.sin(i*2.094)*.025,1.01+Math.cos(i*2.094)*.025,2.343);ray.rotation.z=-i*2.094;g.add(ray);}const shadow=new T.Mesh(new T.PlaneGeometry(2.1,4.9),new T.MeshBasicMaterial({color:0x11191f,transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.045;g.add(shadow);return g;}
 makeBoard(){const g=new T.Group();const deck=this.box(.24,.045,1.05,0x807458);deck.position.y=.12;g.add(deck);this.deck=deck;for(const z of [-.31,.31])for(const x of [-.15,.15]){const w=new T.Mesh(new T.CylinderGeometry(.045,.045,.04,8),this.mat(0xbaad8b));w.rotation.z=Math.PI/2;w.position.set(x,.055,z);g.add(w);}return g;}
 makeRider(){const g=new T.Group();this.hips=new T.Group();g.add(this.hips);this.torso=this.box(.42,.53,.25,0x27282b);this.torso.position.y=1.17;this.hips.add(this.torso);this.head=new T.Mesh(new T.SphereGeometry(.135,9,6),this.mat(0xc4a282));this.head.position.set(0,1.64,-.015);this.hips.add(this.head);this.hair=new T.Mesh(new T.SphereGeometry(.14,9,6,0,Math.PI*2,0,Math.PI*.57),this.mat(0x332921));this.hair.position.copy(this.head.position);this.hips.add(this.hair);this.limbs=[];for(let i=0;i<8;i++){const m=this.cylinder(.052,.057,1,i<4?0x2c3339:i<6?0x27282b:0xc4a282,6);this.hips.add(m);this.limbs.push(m);}this.shoes=[];for(let i=0;i<2;i++){const m=this.box(.15,.1,.27,0x20262b);g.add(m);this.shoes.push(m);}return g;}
 limb(index,a,b){const m=this.limbs[index],va=new T.Vector3(...a),vb=new T.Vector3(...b);m.position.copy(va).add(vb).multiplyScalar(.5);m.scale.y=va.distanceTo(vb);m.quaternion.setFromUnitVectors(UP,vb.sub(va).normalize());}
 setSelection(o){const c=RIDERS[o.rider];this.torso.material=this.mat(c.shirt);this.hair.material=this.mat(c.hair);for(let i=0;i<4;i++)this.limbs[i].material=this.mat(c.pants);this.deck.scale.z=BOARDS[o.board].length/1.05;this.deck.material=this.mat(o.board==='CRUISER'?0x9b5945:o.board==='STREET'?0x5d676a:0x807458);}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 draw(sim,dt,input={},menu=false){const c=sim.car,r=sim.rider,ground=height(r.x,r.z),crashed=sim.phase==='crashed'||sim.phase==='ended',crouch=input.crouch&&!crashed;
  this.car.position.set(c.x,height(c.x,c.z),c.z);this.car.rotation.y=-c.heading-Math.PI/2;const fore=sample(c.s+1),aft=sample(c.s-1);this.car.rotation.x=Math.atan2(height(fore.x,fore.z)-height(aft.x,aft.z),2)*-1;
  const h=r.heading;this.rider.position.set(r.x,ground+r.height+.08,r.z);this.rider.rotation.set(0,-h-Math.PI/2,crashed?Math.min(sim.phaseTime*2,1.5):0);this.rider.position.y=crashed?ground+.28:ground+r.height+.08;
  const lean=r.lean+Math.sin(sim.time*22)*r.wobble*.09,cy=crouch?.28:0;this.hips.position.set(lean*.22,-cy,0);this.torso.rotation.z=-lean*.6;this.head.position.x=lean*.26;this.hair.position.copy(this.head.position);
  this.limb(0,[-.13,.94,0],[-.17,.54+cy*.25,.08]);this.limb(1,[-.17,.54+cy*.25,.08],[-.15,.14+cy,.24]);this.limb(2,[.13,.94,0],[.17,.54+cy*.25,-.13]);this.limb(3,[.17,.54+cy*.25,-.13],[.15,.14+cy,-.22]);this.shoes[0].position.set(-.15,.12,.24);this.shoes[1].position.set(.15,.12,-.22);
  const handY=.92+cy*.5,handZ=r.holding?-.48:0;this.limb(4,[-.22,1.38,0],[-.28,1.08,-.22]);this.limb(5,[.22,1.38,0],[.28,1.08,-.22]);this.limb(6,[-.28,1.08,-.22],[-.17,handY,handZ]);this.limb(7,[.28,1.08,-.22],[.17,handY,handZ]);
  const bp=sim.board??r;this.board.position.set(bp.x,height(bp.x,bp.z)+(crashed?.04:r.height),bp.z);this.board.rotation.set(0,-bp.heading-Math.PI/2,crashed?sim.phaseTime*.9:lean*.25);
  const hx=r.x+Math.cos(h)*.48,hz=r.z+Math.sin(h)*.48,hy=ground+r.height+handY-cy+.08;
  this.rope.visible=r.holding;this.handle.visible=r.holding;this.handle.position.set(hx,hy,hz);this.handle.rotation.y=-h-Math.PI/2;
  if(r.holding){const slack=clamp(sim.rope-Math.hypot(c.hx-r.x,c.hz-r.z),0,1.8);for(let i=0;i<33;i++){const t=i/32,x=mix(c.hx,hx,t),z=mix(c.hz,hz,t);this.ropePositions[i*3]=x;this.ropePositions[i*3+1]=Math.max(height(x,z)+.055,mix(height(c.hx,c.hz)+.39,hy,t)-Math.sin(t*Math.PI)*(.12+slack*.7));this.ropePositions[i*3+2]=z;}this.rope.geometry.attributes.position.needsUpdate=true;}
  for(const t of this.tails)t.material.color.setHex(c.brake||crashed?0xff4b2b:0x8e382f);
  // Bearing includes rope swing but is damped independently from translation.
  const bearing=r.holding?Math.atan2(c.z-r.z,c.x-r.x):r.heading;const desired=heading(c.s)+angle(bearing-heading(c.s))*.4;
  this.camHeading+=angle(desired-this.camHeading)*(1-Math.exp(-dt*2.8));
  const behind=menu?10:8;const tx=r.x-Math.cos(this.camHeading)*behind-Math.sin(this.camHeading)*1.1,tz=r.z-Math.sin(this.camHeading)*behind+Math.cos(this.camHeading)*1.1;
  const ty=ground+(menu?4.1:3.85);if(!this.camPos)this.camPos=new T.Vector3(tx,ty,tz);this.camPos.lerp(new T.Vector3(tx,ty,tz),1-Math.exp(-dt*5));this.camera.position.copy(this.camPos);
  this.camera.lookAt(this.camPos.x+Math.cos(this.camHeading)*24,ground+(menu?2.4:1.6),this.camPos.z+Math.sin(this.camHeading)*24);
  this.sky.position.copy(this.camera.position);const evening=clamp(sim.time/550,0,1);this.sky.material.uniforms.top.value.set('#536b83').lerp(new T.Color('#111d36'),evening);this.sky.material.uniforms.bottom.value.set('#b99d8d').lerp(new T.Color('#485b73'),evening);this.scene.fog.color.set('#586974').lerp(new T.Color('#34445b'),evening);this.sunlight.intensity=mix(.85,.15,evening);this.hemi.intensity=mix(1.3,.75,evening);for(const l of this.lamps)if(l.material.transparent)l.material.opacity=.06+evening*.13;
  if(new URLSearchParams(location.search).has('entrance-review')){this.camera.position.set(100,115,-15);this.camera.lookAt(28,0,-61);this.sky.position.copy(this.camera.position);}
  this.renderer.render(this.scene,this.camera);
 }
}

