import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const events={},stores=new Map(),base='https://track.test/the-track-2008/',normal=u=>new URL(typeof u==='string'?u:u.url,base).href;let online=true,claimed=false,skip=false;const navigated=[];
const fakeFetch=async req=>{if(!online)throw Error('offline');const p=new URL(normal(req)).pathname.replace('/the-track-2008/','');const file='./'+(p===''?'index.html':p);if(!fs.existsSync(file))return new Response('missing',{status:404});return new Response(fs.readFileSync(file),{status:200});};
const caches={async open(name){if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return{async addAll(urls){for(const url of urls){const r=await fakeFetch(url);assert(r.ok,`asset missing: ${url}`);store.set(normal(url),r);}},async put(url,r){store.set(normal(url),r);}};},async keys(){return [...stores.keys()];},async delete(name){return stores.delete(name);},async match(url){for(const store of stores.values())if(store.has(normal(url)))return store.get(normal(url)).clone();}};
const context={self:{location:{origin:'https://track.test'},registration:{scope:base},async skipWaiting(){skip=true;},clients:{async claim(){claimed=true;},async matchAll(){return[{url:base,navigate:async url=>navigated.push(url)},{url:'https://track.test/another-game/',navigate:async url=>navigated.push(url)}];}},addEventListener:(n,fn)=>events[n]=fn},caches,fetch:fakeFetch,Response,URL};vm.runInNewContext(fs.readFileSync('service-worker.js','utf8'),context);
let pending;events.install({waitUntil:p=>pending=p});await pending;const all=[...stores.values()][0];assert.equal(all.size,13);
stores.set('track-2008-old',new Map());stores.set('the-track-proto-02-v1',new Map());stores.set('unrelated-cache',new Map());events.activate({waitUntil:p=>pending=p});await pending;assert(claimed);assert(skip);assert(!stores.has('track-2008-old'));assert(!stores.has('the-track-proto-02-v1'));assert(stores.has('unrelated-cache'));assert.deepEqual(navigated,[base]);
online=false;for(const url of ['/', '/app.js','/render.js','/vendor/three.module.js','/vendor/three.core.js','/icon-192.png']){let response;events.fetch({request:{method:'GET',url:base.slice(0,-1)+url,mode:url==='/'?'navigate':'cors'},respondWith:p=>response=p});const r=await response;assert(r?.ok,`offline failed: ${url}`);assert((await r.arrayBuffer()).byteLength>0);}
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest'));assert.equal(manifest.display,'standalone');assert.equal(manifest.start_url,'./');assert(manifest.icons.every(i=>fs.existsSync('./'+i.src)));
console.log('PASS All 13 core assets precache under a GitHub Pages subpath; offline fallbacks; legacy cache migration; only in-scope legacy pages refreshed');


