import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Ride,STEP} from '../physics.js';
import {Gestures} from '../input.js';
import {roadDistance,route,LENGTH,CUL_START,RIDERS,BOARDS,angle,heading} from '../world.js';
const results=[];function test(name,fn){try{const details=fn();results.push({name,pass:true,details});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.message);process.exitCode=1;}}
function advance(sim,seconds,input={}){for(let i=0;i<Math.round(seconds/STEP);i++)sim.step(input);return sim;}
test('Car footprint fits the independently defined paved surface',()=>{let worst=-Infinity;for(const p of route){const h=heading(p.s);for(const a of [-2.31,2.31])for(const b of [-.89,.89]){const d=roadDistance(p.x+Math.cos(h)*a-Math.sin(h)*b,p.z+Math.sin(h)*a+Math.cos(h)*b);worst=Math.max(worst,d);}}assert(worst<0,`car corner outside asphalt: ${worst}`);return{minimumClearance:-worst};});
test('Driver heading is continuous including bulb throat and lap boundary',()=>{let max=0;for(let s=0;s<LENGTH;s+=.1)max=Math.max(max,Math.abs(angle(heading(s+.1)-heading(s))));assert(max<.1,`heading jump ${max}`);return{maxHeadingChangePer10cm:max};});
test('Default no-input combinations survive a full lap',()=>{const rows=[];for(const rider of Object.keys(RIDERS))for(const board of Object.keys(BOARDS)){const s=new Ride({rider,board,rope:.45,seed:8});for(let i=0;i<120*200&&s.laps<1&&s.phase==='riding';i++)s.step();rows.push({rider,board,phase:s.phase,lap:s.laps,maxStretch:s.stats.maxStretch,maxAhead:s.stats.maxAhead});assert.equal(s.phase,'riding',`${rider}/${board}: ${s.stats.crashReason} at ${s.car.s}`);assert.equal(s.laps,1);assert(s.stats.maxStretch<.1);assert(s.stats.maxAhead<-2.5);assert(s.stats.maxStep<.15);}return rows;});
test('Short, medium and long longboard ropes survive two laps with both drivers',()=>{const rows=[];for(const rider of ['DOG','SALLY'])for(const rope of [0,.5,1]){const s=new Ride({rider,rope});for(let i=0;i<120*300&&s.laps<2&&s.phase==='riding';i++)s.step();assert.equal(s.laps,2,`${rider}/${rope}`);assert.equal(s.phase,'riding');rows.push({rider,rope,seconds:s.time,maxStretch:s.stats.maxStretch});}return rows;});
test('SALLY is faster; DOG bursts vary by seeded lap',()=>{const s=new Ride({rider:'DOG'}),d=new Ride({rider:'SALLY',seed:2}),fast=new Ride({rider:'SALLY',seed:8});assert(s.targetSpeed()>d.targetSpeed());assert(fast.targetSpeed()>d.targetSpeed());return{SALLY:s.targetSpeed(),DOG:d.targetSpeed(),DOGBurst:fast.targetSpeed()};});
test('Release preserves position, heading and momentum at the instant of letting go',()=>{const s=advance(new Ride(),12),r={...s.rider};assert(s.release());assert.equal(s.rider.vx,r.vx);assert.equal(s.rider.vz,r.vz);assert.equal(s.rider.x,r.x);assert.equal(s.rider.z,r.z);assert.equal(s.rider.heading,r.heading);s.step();assert.equal(s.rider.tension,0);assert.equal(s.rider.holding,false);return{releaseSpeed:Math.hypot(r.vx,r.vz)};});
test('Early straight release coasts to a safe regroup',()=>{const s=advance(new Ride(),10);s.release();advance(s,60);assert.equal(s.phase,'regroup');return{seconds:s.time};});
test('Steering affects motion; sustained bad steering causes a continuous physical failure',()=>{const s=advance(new Ride({board:'STREET',rope:1}),10);let maxStep=0;for(let i=0;i<120*10&&s.phase==='riding';i++){const x=s.rider.x,z=s.rider.z;s.step({steer:1});maxStep=Math.max(maxStep,Math.hypot(s.rider.x-x,s.rider.z-z));}assert.equal(s.phase,'crashed');assert(maxStep<.15);const x=s.rider.x,z=s.rider.z;advance(s,.2);assert(Math.hypot(s.rider.x-x,s.rider.z-z)>0);return{reason:s.stats.crashReason,maxStep};});
test('Aggressive cul-de-sac setup can fail while conservative setup survives',()=>{const rows=[];for(const factor of [1,1.7,2.1]){const s=new Ride({rider:'DOG',board:'STREET',rope:1,start:CUL_START-70,speedFactor:factor});for(let i=0;i<120*60&&s.car.s<CUL_START+90&&s.phase==='riding';i++)s.step();rows.push({factor,phase:s.phase,reason:s.stats.crashReason,s:s.car.s});}assert.equal(rows[0].phase,'riding');assert(rows.slice(1).some(r=>r.phase==='crashed'));return rows;});
test('Ollie permissions cover all rider / board combinations',()=>{for(const rider of Object.keys(RIDERS))for(const board of Object.keys(BOARDS)){const s=new Ride({rider,board});assert.equal(s.ollie(),RIDERS[rider].ollie&&BOARDS[board].ollie,`${rider}/${board}`);if(s.rider.up){advance(s,.1);assert(s.rider.height>0);assert(s.rider.holding);}}});
test('Fixed-step results agree at 30, 60 and 120 display frames per second',()=>{const states=[];for(const fps of [30,60,120]){const s=new Ride();let acc=0;for(let frame=0;frame<fps*20;frame++){acc+=1/fps;while(acc>=STEP-1e-12){s.step({steer:Math.sin(s.time)*.04});acc-=STEP;}}states.push(s.snapshot());}assert.deepEqual(states[0],states[1]);assert.deepEqual(states[0],states[2]);});
test('Gestures distinguish crouch-lift, carving, up-flick, cancel and second pointer',()=>{let releases=0,ollies=0;const g=new Gestures({release:()=>releases++,ollie:()=>ollies++});g.down(1,100,500,0);g.tick(240);assert(g.state.crouch);g.up(1,250);assert.equal(ollies,1);assert.equal(releases,0);g.down(1,100,500,300);g.move(1,180,492,350);g.up(1,360);assert.equal(releases,0);assert.equal(ollies,1);g.down(1,100,500,400);g.move(1,103,440,480);assert.equal(releases,1);g.up(1,490);assert.equal(ollies,1);g.down(1,100,500,500);g.down(2,200,500,510);g.move(2,200,420,550);assert.equal(releases,1);g.tick(750);g.cancel(1);assert.equal(ollies,1);assert.equal(g.pointer,null);});
fs.mkdirSync('test-results',{recursive:true});fs.writeFileSync('test-results/physics.json',JSON.stringify(results,null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} passed`);

